services:
  postgres-db:
    container_name: postgres-db
    image: postgres:17.4-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB=ost
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    secrets:
      - postgres_password

volumes:
  postgres_db:

secrets:
  postgres_password:
    file: ./.env